version: "3.7"
services:
  finance_ai_service:
    build: .
    container_name: finance-ai-service
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      bash -c "uvicorn src.app.main:app --host 0.0.0.0 --port 8000"
